### ISSUE TITLE
Asset Container [shopify] not found 

### ISSUE THREAD

**Issue by devravik** [damcclean/simple-commerce#544] opened 2022-01-12 18:17 UTC
### Bug Description

Hi, me again, Got another issue, this is while creating new entry to Product collection

![image](https://user-images.githubusercontent.com/41594847/149198355-53ab4e04-b6d9-44ba-9556-68475b6e09d2.png)

### Steps to reproduce

Collection > Products > Create

### Environment

Statamic 3.2.30 Pro
Laravel 8.79.0
PHP 7.4.27
doublethreedigital/simple-commerce 2.3.62
spatie/statamic-responsive-images 2.8.5
statamic/seo-pro 2.3.2
xndbogdan/statamic-bard-text-color 2.2

**Comment by duncanmcclean** [comment] 2022-01-12 18:29
How did you install Simple Commerce? 

I don't think this is an issue with Simple Commerce.

**Comment by devravik** [comment] 2022-01-12 18:32
Just followed standard install

![image](https://user-images.githubusercontent.com/41594847/149200721-f5a7a0cc-aa4e-4535-b5a1-44bd69385f2e.png)
![image](https://user-images.githubusercontent.com/41594847/149200804-d994a6e3-7c3a-48ba-a1d5-c5646d3ec0b8.png)

**Comment by duncanmcclean** [comment] 2022-01-12 18:33
Did you install the Shopify addon, then uninstall it?

Because if you have, I don't think you uninstalled it properly which is likely the cause of your issues.

**Comment by duncanmcclean** [comment] 2022-01-12 18:36
Did you install the Shopify addon, then uninstall it?

Because if you have, I don't think you uninstalled it properly which is likely the cause of your issues.

**Comment by duncanmcclean** [comment] 2022-01-13 09:19
Closing this as I believe the Shopify addon has previously been installed and was then uninstalled, leaving behind it's fields in Blueprints etc.

**Closed as completed by duncanmcclean** 2022-01-13 09:19 UTC
