### ISSUE TITLE
 'Call to a member function entryBlueprint() on null' after database import

### ISSUE THREAD

**Issue by stoffelio** [damcclean/simple-commerce#813] opened 2023-02-13 14:15 UTC
### Description

As explained on Discord, after importing customers and orders to the database, it is not possible to show/edit a single order in the control panel. Accessing a route such as /cp/runway/orders/19 results in the following error:

[2023-02-13 14:12:20] development.ERROR: Call to a member function entryBlueprint() on null {"userId":"4d1ad0d9-4ct8-462f-b0f8-1dd6b650b7fb","exception":"[object] (Error(code: 0): Call to a member function entryBlueprint() on null at /vendor/statamic/cms/src/Fieldtypes/Entries.php:109)
[stacktrace]
#0 /vendor/statamic/cms/src/Fieldtypes/Entries.php(295): Statamic\\Fieldtypes\\Entries->getBlueprint()
#1 /vendor/statamic/cms/src/Fieldtypes/Relationship.php(120): Statamic\\Fieldtypes\\Entries->getColumns()
#2 /vendor/statamic/cms/src/Fields/Field.php(408): Statamic\\Fieldtypes\\Relationship->preload()
#3 /vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(60): Statamic\\Fields\\Field->meta()
#4 [internal function]: Illuminate\\Support\\HigherOrderCollectionProxy->Illuminate\\Support\\{closure}()
#5 /vendor/laravel/framework/src/Illuminate/Collections/Arr.php(560): array_map()
#6 /vendor/laravel/framework/src/Illuminate/Collections/Collection.php(774): Illuminate\\Support\\Arr::map()
#7 /vendor/laravel/framework/src/Illuminate/Collections/HigherOrderCollectionProxy.php(59): Illuminate\\Support\\Collection->map()
#8 /vendor/statamic/cms/src/Fields/Fields.php(296): Illuminate\\Support\\HigherOrderCollectionProxy->__call()
#9 /vendor/doublethreedigital/runway/src/Http/Controllers/ResourceController.php(197): Statamic\\Fields\\Fields->meta()
#10 /vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): DoubleThreeDigital\\Runway\\Http\\Controllers\\ResourceController->edit()
#11 /vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(43): Illuminate\\Routing\\Controller->callAction()
#12 /vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\\Routing\\ControllerDispatcher->dispatch()

### Steps to reproduce

Followed the Database migration guide from the documentation.

### Environment

Environment
Application Name: [Staging] -
Laravel Version: 9.51.0
PHP Version: 8.2.1
Composer Version: 2.5.3
Environment: development
Debug Mode: ENABLED
URL: -
Maintenance Mode: OFF

Cache
Config: NOT CACHED
Events: NOT CACHED
Routes: NOT CACHED
Views: CACHED

Drivers
Broadcasting: log
Cache: statamic
Database: mysql
Logs: stack / daily
Mail: smtp
Queue: sync
Session: file

Simple Commerce
Currencies: EUR
Gateways: Mollie
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EloquentCustomerRepository
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EloquentOrderRepository
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository
Shipping Methods: Standardversand - 3-4 Werktage, Einschreiben Einwurf - 3-4 Werktage, Expressversand - bis zu 48h, Kurier (nur Berlin) - am selben Tag
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\BasicTaxEngine

Statamic
Addons: 2
Antlers: regex
Stache Watcher: Enabled
Static Caching: Disabled
Version: 3.3.65 PRO

Statamic Addons
doublethreedigital/runway: 2.6.7
doublethreedigital/simple-commerce: 4.5.3

**Comment by duncanmcclean** [comment] 2023-02-13 17:10
Thanks for reporting this!

It looks like it's being caused by the Coupon fieldtype - looking into sorting it now! :)

**Comment by duncanmcclean** [comment] 2023-02-13 17:15
Ah, seems like I forgot to change the Runway blueprint after making a change in v4.

Replace the `coupon` field in your Order blueprint with this:

```yaml
- handle: coupon
  field:
     max_items: 1
     mode: default
     type: coupon
     display: Coupon
     width: 50
     visibility: read_only
```

The default blueprint will be fixed in the next release.

**Closed as completed by duncanmcclean** 2023-02-13 17:15 UTC
Labels: bug, database
