### ISSUE TITLE
Zero percent tax bug(s)

### ISSUE THREAD

**Issue by jamie-b5** [damcclean/simple-commerce#1038] opened 2024-04-03 08:58 UTC
### Description

Our client has added a zero percent (0%) tax category for pre-loved (second hand) items. This seems to produce 2 bugs.

**Bug 1 - Trying to access array offset on value of type null**

At point of adding product to basket (one using the zero tax rate).

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/a397139d-9f6d-4e98-8f08-156c081e6751)

Bug 2 

(may or may not be related to the zero tax category).

In admin ->Products Index, customizing the columns to include Tax Category then refreshing the view displays the error 

Call to a member function id() on null

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/a38cc8bc-b8a7-4843-ab73-6af625a566dc)

and the products disappear!

Thanks in advance!

Jamie

### Steps to reproduce

**Bug 1: Zero tax product in basket**

Create a tax rate with zero percent.

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/60b0fa0c-738c-4d10-a444-b045155da03b)

Assign this to a product

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/41a2504c-c46e-4c0c-b9b1-1a0efb04b71b)

Add this product to your basket on the front end and we receive the error:

_Trying to access array offset on value of type null_

**Bug 2: customizing columns with tax category (may be related?)**

In the admin, go to products index and click customize columns.

Add in the tax category

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/51b083f0-5d5a-4872-b6f4-05e4636f70fa)

Refresh the index view

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/a38cc8bc-b8a7-4843-ab73-6af625a566dc)

Error is _Call to a member function id() on null_

If you remove the Tax Category from the customized columns the products are visible again.

### Environment

This is my dev environment - same issue. I have a license for the production version FYI!

Environment                                                                                  
Application Name: Sound Organisation                                                         
Laravel Version: 10.22.0                                                                     
PHP Version: 8.1.10                                                                          
Composer Version: 2.4.1                                                                      
Environment: local                                                                           
Debug Mode: ENABLED                                                                          
URL: sound_org.test                                                                          
Maintenance Mode: OFF                                                                        
                                                                                             
Cache                                                                                        
Config: NOT CACHED                                                                           
Events: NOT CACHED                                                                           
Routes: NOT CACHED                                                                           
Views: CACHED                                                                                
                                                                                             
Drivers                                                                                      
Broadcasting: log                                                                            
Cache: statamic                                                                              
Database: mysql                                                                              
Logs: stack / single                                                                         
Mail: smtp                                                                                   
Queue: sync                                                                                  
Session: file                                                                                
                                                                                             
Simple Commerce                                                                              
Currencies: GBP                                                                              
Gateways: Stripe                                                                             
Repository: Customer: DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository    
Repository: Order: DoubleThreeDigital\SimpleCommerce\Orders\EntryOrderRepository             
Repository: Product: DoubleThreeDigital\SimpleCommerce\Products\EntryProductRepository       
Shipping Methods: Free Overnight Shipping, Click and Collect                                 
Tax Engine: DoubleThreeDigital\SimpleCommerce\Tax\Standard\TaxEngine                         
                                                                                             
Statamic                                                                                     
Addons: 3                                                                                    
Antlers: runtime                                                                             
Stache Watcher: Disabled                                                                     
Static Caching: Disabled                                                                     
Version: 4.21.0 PRO                                                                          
                                                                                             
Statamic Addons                                                                              
doublethreedigital/simple-commerce: 5.6.2                                                    
jezzdk/statamic-google-maps: 1.2.2                                                           
rias/statamic-data-import: 1.3.0

**Comment by duncanmcclean** [comment] 2024-04-03 09:22
Thanks for reporting this! I'll take a look when I have some time.

**Comment by duncanmcclean** [comment] 2024-04-04 19:35
Hey 👋

I'm unable to reproduce this issue using the latest version of Simple Commerce, [v6.0.11](https://github.com/duncanmcclean/simple-commerce/releases/tag/v6.0.11).

Are you able to try updating to see if that fixes the issue for you? Thanks.

**Comment by jamie-b5** [comment] 2024-04-05 08:22
Hi Duncan

Thanks for trying to reproduce the issue. I will upgrade to the latest
version and see what happens.

Thanks

Jamie

**Comment by duncanmcclean** [comment] 2024-04-06 17:36
I'm going to close this issue for the time being. Let me know if it doesn't fix the issue for you and I can re-open. Thanks!

**Closed as completed by duncanmcclean** 2024-04-06 17:36 UTC
Labels: bug, needs more info, taxes

**Comment by jamie-b5** [comment] 2024-04-08 10:41
Hi Duncan

I have upgraded to 5.9.2 and the error is still occurring. 5.9.2 is the highest version composer will allow me to update to.

If I specify the version 6.0.11 in the composer update command I receive the following error:

**Class "DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository" not found**

I have updated core statamic to 4.55 (the latest as far as I am aware).

Any help greatly appreciated.

Thanks

Jamie

**Comment by duncanmcclean** [comment] 2024-04-08 11:04
Did you follow the upgrade guide when updating? https://simple-commerce.duncanmcclean.com/upgrade-guides/v5-x-to-v6-0

**Comment by jamie-b5** [comment] 2024-04-08 11:16
Apologies, not spotted that.

I'll work through and update you.

Much appreciated.

**Comment by jamie-b5** [comment] 2024-04-08 11:21
Followed the steps in the guide but am still seeing an error.

`Class "DoubleThreeDigital\SimpleCommerce\Customers\EntryCustomerRepository" not found                                               
                                                                                                                                    
at C:\laragon\www\servers\statamic-staging\sound_org\vendor\statamic\cms\src\Statamic.php:380                                       
  376▕     public static function repository($abstract, $concrete)                                                                  
  377▕     {                                                                                                                        
  378▕         app()->singleton($abstract, $concrete);                                                                              
  379▕                                                                                                                              
➜ 380▕         foreach ($concrete::bindings() as $abstract => $concrete) {                                                          
  381▕             app()->bind($abstract, $concrete);                                                                               
  382▕         }                                                                                                                    
  383▕     }                                                                                                                        
  384▕                                                                                                                              
                                                                                                                                    
1   C:\laragon\www\servers\statamic-staging\sound_org\vendor\duncanmcclean\simple-commerce\src\ServiceProvider.php:237              
    Statamic\Statamic::repository("DuncanMcClean\SimpleCommerce\Contracts\CustomerRepository", "DoubleThreeDigital\SimpleCommerce\Cu
ntryCustomerRepository")                                                                                                            
                                                                                                                                    
2   C:\laragon\www\servers\statamic-staging\sound_org\vendor\laravel\framework\src\Illuminate\Foundation\Application.php:1038       
    DuncanMcClean\SimpleCommerce\ServiceProvider::DuncanMcClean\SimpleCommerce\{closure}(Object(Illuminate\Foundation\Application)) `

Have also tried to re-run scripts with _php please sc:run-update-scripts_

**Comment by duncanmcclean** [comment] 2024-04-08 11:22
In your `simple-commerce.php` config file, do a find & replace and change `DoubleThreeDigital` to `DuncanMcClean`.

**Comment by jamie-b5** [comment] 2024-04-08 11:28
I have done that but I'm still seeing errors

```
 Class "DoubleThreeDigital\SimpleCommerce\Shipping\BaseShippingMethod" not found

  at C:\laragon\www\servers\statamic-staging\sound_org\app\ShippingMethods\FreeOvernightShippingMethod.php:10
```

Do I need to manually find and replace all occurrences of DoubleThreeDigital with DuncanMcClean in the codebase?

Thanks

**Comment by duncanmcclean** [comment] 2024-04-08 11:37
> Do I need to manually find and replace all occurrences of DoubleThreeDigital with DuncanMcClean in the codebase?

Yes, [you will need to](https://simple-commerce.duncanmcclean.com/upgrade-guides/v5-x-to-v6-0#content-high-namespace-has-changed).

**Comment by jamie-b5** [comment] 2024-04-08 15:39
Hi Duncan

Some progress. I have managed to upgrade to 6.0.11 but still seeing some issues.

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/738e9715-bda9-4376-9f0b-05a33f01d3ec)

The cart now reports a generic 500 error for any products added

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/6f8549b6-d0d2-46fd-a673-9b44511f61b8)

This is reporting from the url http://sound_org.test/!/simple-commerce/cart-items is this a javascript function?

Also I am trying to run the update scripts as I noticed that the orders files needed to update their reference to the payment gateways etc but this seems to be taking a very long time to run (feels like it's hanging?)

![image](https://github.com/duncanmcclean/simple-commerce/assets/48086633/d92c6248-7162-4b20-a60f-bf9840e48eb4)

Thanks again

**Comment by duncanmcclean** [comment] 2024-04-08 18:18
> The cart now reports a generic 500 error for any products added
> This is reporting from the url http://sound_org.test/!/simple-commerce/cart-items is this a javascript function?

Unfortunately, that's not much for me to go on. Are you able to open a new issue for this and include anything from your log file (in `storage/logs`)?

> Also I am trying to run the update scripts as I noticed that the orders files needed to update their reference to the payment gateways etc but this seems to be taking a very long time to run (feels like it's hanging?)

If you have lots of orders, this is to be expected. It has to loop over all of them and update the data.

**Comment by jamie-b5** [comment] 2024-04-09 08:47
Thanks Duncan. I'll open a new issue and see if I can find more detail in the logs.
